### ISSUE TITLE
New package name? like hdmtn

### ISSUE THREAD

**Issue by Zhenyu028** [suchard-group/largeMTN#5]
As pointed out by @aki-nishimura , "hd" may be more suitable than "large" to indicate "high-dimensional" (which seems to be the case for most packages on CRAN). So I'm thinking to change the package name to hdmtn also to avoid mixing lower and upper cases.

**Comment by aki-nishimura** [comment]
Or `hdtn` is also a possibility since "high-dimensional" and "multivariate" are somewhat redundant. Incidentally, we might also change the repo name accordingly.

**Comment by Zhenyu028** [comment]
That's true ... just there exists a `HDTN` package. Maybe `hdtg`, g for Gaussian? And yes I'll remember to change the repo name and also those in docs and manuscript.

**Comment by aki-nishimura** [comment]
I like the `hdtg` idea 👍
On May 1, 2022, 12:53 PM +0900, Zhenyu Zhang ***@***.***>, wrote:

External Email - Use Caution



That's true ... just there exists a HDTN package. Maybe hdtg, g for Gaussian? And yes I'll remember to change the repo name and also those in docs and manuscript.

**Comment by Zhenyu028** [comment]
We decided on `hdtg`, will make the change.
