### ISSUE TITLE
Allow random travel time for hhmc

### ISSUE THREAD

**Issue by Zhenyu028** [suchard-group/largeMTN#6]
Currently hhmc function takes a fixed travel time (default = pi/2). On some test cases we noticed a potential periodicity issue and drawing a travel time from uniform(pi/8, pi/2) for each iteration gives a much better performance. So we may want to add such a choice (and possibly let the user choose the uniform boundary?)

**Comment by chinandrew** [comment]
Do you think it's sufficient to do just a uniform distribution, or do we also need to worry about users who want to sample from other distributions? For the latter, we might want to do something where the user passes in a random function that we call, but that's a bit more complicated of an interface than setting two values.

If just uniform, is there a preference between:
1. Just have the lower and upper bound arguments as you suggest, and for constant time they can set them to be the same. 
2. Have 3 arguments, one if they want a fixed time and a mutually exclusive pair of arguments for lower/upper if they want uniform.

**Comment by Zhenyu028** [comment]
I'd say a uniformly distributed travel time is enough. I like the 3 arguments better, and we might make them all optional and use [pi/8, pi/2] as a default if none of the 3 arguments is provided.

**Comment by aki-nishimura** [comment]
Or, how about a single argument, which takes a scalar or vector of length 2? That might be cleaner.

**Comment by chinandrew** [comment]
> Or, how about a single argument, which takes a scalar or vector of length 2? That might be cleaner.

Oh that's an interesting suggestion, I like that

**Comment by aki-nishimura** [comment]
Also, how sure are we about `[pi / 8, pi / 2]` as the default? Results from one example won't provide a strong support, and I am still surprised that we need to jitter that much. For that example, I'd suspect `[pi / 8, pi / 4]` would mix just as well. 

Perhaps `pi / 2` is too large under typical constraints b/c the space isn't as large as the unconstrained case, but not clear what a reasonable default is. Ideally, we would do a bit more systematic investigation, but that will take time. Perhaps jittering around `pi / 4`(e.g. `[3 / 8 * pi, 5 / 8 * pi]`) is a reasonable choice to start and we can always change the default. Thought @Zhenyu028 ?

**Comment by Zhenyu028** [comment]
You are right, a more thorough comparison is necessary to pick the default travel time. Just I'm not sure if I have time for that in the next few days. From the few CS examples I tested the performance is `[pi/8, pi/2]>[pi/4, pi/2]>[pi/8, pi/4]`. So I'd suggest we use `[pi/8, pi/2]`and change it soon when I get to test other options?

**Comment by aki-nishimura** [comment]
> So I'd suggest we use `[pi/8, pi/2]`and change it soon when I get to test other options?

Sounds good!
